host: sg.ix.hypernology.com
port: 3306
database: crystal_mc #should be same as hypernitemc-core
username: crystal
password: crystal66451700
use-SSL: false
Pool:
  name: HyperNiteMC-Pool
  min-size: 5
  max-size: 10